### ISSUE TITLE
v1.9.3/v1.9.4-rc4: Incorrect In-Reply-To: and References: headers in replies

### ISSUE THREAD

**Issue by perhov** [osTicket/osTicket-1.8#1346]
Hi, I have noticed that the emails sent to a user when a staff posts a reply to a ticket don't thread properly in the user's mail client. When turning on message threading in for example Mozilla Thunderbird, none of the messages belonging to the ticket are displayed as a single thread. (The problem is masked/does probably not appear in Gmail and other mail clients which use other threading algorithms). The patch below fixes the problem.

This reason the emails don't thread is because both the In-Reply-To: and References headers in the reply contain the wrong values. Today, the In-Reply-To: header contains the message ID of the response message itself (an internal osTicket ID which the user's mail client has never seen), instead of the message ID of the email that the staff is responding to. The References: header contains the same value, a single message ID which is the internal/auto-generated message ID of the response.

This patch changes the behaviour of the `postReply()` method so that these headers refer to the most recent email from the user: The In-Reply-To: header now refers to the Message ID of the last *message* in the ticket (and does not consider *internal notes* or *replies*), and the References: header now contains the References: header from the last message in the ticket plus the message ID from the same message.

Patch for v1.9.3:

    diff -r daf8d455c5b0 include/class.ticket.php
    --- a/include/class.ticket.php      Fri Sep 26 14:13:30 2014 +0200
    +++ b/include/class.ticket.php      Tue Sep 30 11:48:48 2014 +0200
    @@ -1764,8 +1764,8 @@
                     'staff' => $thisstaff,
                     'poster' => $thisstaff);
             $options = array(
    -                'inreplyto' => $response->getEmailMessageId(),
    -                'references' => $response->getEmailReferences(),
    +                'inreplyto' => $this->getLastMessage()->getEmailMessageId(),
    +                'references' => $this->getLastMessage()->getEmailReferences(),
                     'thread'=>$response);
     
             if(($email=$dept->getEmail())

The code in v1.9.4-rc4 looks very similar, so the same issue is probably present there (see line ~1855).

**Comment by aklein-dex** [comment]
I could notice the same problem in v1.9.5.1. When I was replying using osTicket, the email sent was in a different thread in Gmail.
Applying your patch fix the issue. Thanks!

**Comment by greezybacon** [comment]
I think this is properly fixed in v1.9.6. Can anyone confirm?

**Comment by perhov** [comment]
Hi, I have tested in v1.9.7, and it is only partly fixed. The "In-Reply-To:" header is properly fixed, but the "References:" header is now empty.

Expected behaviour for back-and-forth correspondence:
~~~
Message 1: Original message from user to osTicket:
   Message-ID: A
   (No In-Reply-To: or References: headers)

Message 2: Reply from osTicket:
  Message-ID: B
  In-Reply-To: A
  References: A

Message 3: User replies to message 2:
  Message-ID: C
  In-Reply-To: B
  References: A B

Message 4: Reply from osTicket:
  Message-ID: D
  In-Reply-To: C
  References: A B C
~~~

Observed behaviour:
~~~
Message 1: Original message from user to osTicket:
  Message-ID: A
  (No In-Reply-To: or References: headers)

Message 2: Reply from osTicket:
  Message-ID: B
  In-Reply-To: A
  References:            <--- This field is empty

Message 3: User replies to message 2:
  Message-ID: C
  In-Reply-To: B
  References: B          <--- This field therefore lacks "A"

Message 4: Reply from osTicket:
  Message-ID: D
  In-Reply-To: C
  References:            <--- This field is empty
~~~
and so on.

**Comment by greezybacon** [comment]
@perhov looks like you're right. Could you try the patch in #1947

**Comment by perhov** [comment]
The patch in #1947 seems to fix the problem completely. Thanks!

**Comment by kingapricot** [comment]
I'm still encountering this problem on v1.9.12. Can someone please help me fix this problem. I'm a complete newbie when it comes to OsTicket. How can I apply the said patch on a Windows machine?

**Comment by ntozier** [comment]
@kingapricot  did you check to see if your code has the patch mentioned above?

**Comment by kingapricot** [comment]
@ntozier Where is my code? What is the file name and in what folder? I'm sorry I posses no knowledge about OsTicket

**Comment by ntozier** [comment]
Your code is wherever you installed it.
The patch is linked above https://github.com/osTicket/osTicket-1.8/pull/1947
check the lines mentioned in the one file affected.  include/class.mailer.php

**Comment by kingapricot** [comment]
@ntozier I figured it out thanks, but the said patch didn't work for me unfortunately.
![mailer](https://cloud.githubusercontent.com/assets/16048765/11504371/435093fa-9845-11e5-939b-ea646ff899b8.PNG)

**Comment by kingapricot** [comment]
I have replaced everything in my class.mailer.php with the data on this page
https://github.com/greezybacon/osTicket-1.8/blob/5a42156bf7b2543b7995ba9b86e693f64eda38a5/include/class.mailer.php
Still not working

**Comment by Chefkeks** [comment]
@kingapricot 
Can you post some more info like email client you're using and header info from the emails (message-id, in-reply-to, references)?

Beside, have you tested, what happens when you connect to the mailbox via a different email client? Does it show correctly there?

**Comment by kingapricot** [comment]
@chefkeks, I have tested it in gmail and outlook 2016, Gmail handels the emails as it should, it creates one conversation/thread. In outlook 2016 it does not, see my screenshot in my previous comment. 

This is the info from outlook 2016,
X-MS-Exchange-Organization-Network-Message-Id: e62b49cf-8332-4194-f1b0-08d3014d9139
In-Reply-To: <4152e8c0ab8c490aa659da302abff0a4@ICT-EXCH.riwo-ict.local>
References: <4152e8c0ab8c490aa659da302abff0a4@ICT-EXCH.riwo-ict.local>

**Comment by Chefkeks** [comment]
Using Outlook 2016 too, but disabled the conversation view - so going to enable it again and check how my outlook behaves here.

Beside, we've found that some feature (for what ever reason) have been removed from Outlook (e.g. selecting&copying all attachments with CTRL + A, which worked in every previous version) so I'm not sure whether the Outlook guys "improved" something here as well... ;)

**Comment by Chefkeks** [comment]
Update:
Just tested with Outlook 2016 again... definitely not working, for whatever reason. All I got was a nice little message popup (while playing with the "Conversation" settings) that told me first "Outlook is not responding" and after a few seconds it just said "Restarting Outlook" ... so my feelings are that MS "improved" Outlook 2016 conversation settings... :(

**Comment by kingapricot** [comment]
Thanks for your help. Now I know that this problem is specific to outlook 2016, office just gets worse every year. SBS 2011 isn't even compatible anymore with office 2016.
